### ISSUE TITLE
Missing facility for custom shell scripts to upload zone data.

### ISSUE THREAD

**Issue by kyrian666** [pacoorozco/probind#108]
Hi,

Wondering what happened to the directories templates/v[89-master/ that allowed for a custom shell script to be executed to deploy zones, which was present in earlier v2 versions? Or how they might be re-integrated here?

K.

**Comment by pacoorozco** [comment]
Hi @kyrian666 

What `v2` versions are you referring to? 

The current version is using SFTP to push the files to DNS servers. There's the goal of allowing other push mechanisms, but they have not been coded yet. What would be the one you're looking for?

**Comment by kyrian666** [comment]
Well, SFTP would do the job I guess, but I was rather attached to the idea that you could do a custom shell script to deploy, so you could for example not just copy the zone file but have the script SSH to the remote server and run 'rndc reload <zone name>' for example, or if you weren't doing that, do some echo statements that explain what was being done instead.

The templates/v8-master/reconfig.sh from the vanilla 2.0 version would for example run after the zone has been copied, if you selected the right template for the server type. I'll attach it here for reference.

**Comment by kyrian666** [comment]
Give or take that github won't allow you to upload a .sh file without renaming of course ;)

[reconfig_sh.txt](https://github.com/pacoorozco/probind/files/6375475/reconfig_sh.txt)

**Comment by pacoorozco** [comment]
Bear in mind that this probind version is different from the one you are pointing. It means that with the current approach some features needs some analysis first 😓 

From your description... Should be an approach that we allow you to create the files locally and then (outside this app scope) you would be able to call an script to upload, ssh, whatever?

**Comment by kyrian666** [comment]
Well, I checked the history and it said you rewrote it using the laravel framework or some such (which is excellent work by the way, thanks for providing a UI that works with a current version of PHP rather than an ancient one!). I wasn't able to find out more than that, so I didn't know whether you wanted to just rewrite the UI, or the whole thing.

Obviously I can set up a script to poll a directory, yes, rather than run on change. I think it would be better if it could be a local directory, but that's not a deal breaker.

Thanks for confirming the status, as requested, if you can add a drop to a local directory that would be great, but from my perspective I know what I'm dealing with now and this issue can be closed. Once I've solved my immediate need perhaps I can contribute some code back to facilitate the script stuff, not sure if I'll get time though.

**Comment by garethhumphriesgkc** [comment]
This would be handy.  It would great to be able to, after deploying a file, run a syntax check on it and reload bind if that passes.

**Comment by pacoorozco** [comment]
Hi @garethhumphriesgkc 

You can do it outside `probind`. As I shared previously, `probind` will push the configuration and zone files to the server, then you need to take care to promote this files and relaunch BIND.

In my case, I only update the DNS twice per day, so I've an script (trigger by cron) that move the files provided by `probind` to the folder that my BIND is using. Before restarting the BIND, it does a check-zone to each zone file.
