### ISSUE TITLE
Record:getResourceRecord() doesn't handle priority?

### ISSUE THREAD

**Issue by ericb-summit** [pacoorozco/probind#112]
I am trying to use this tool, migrated the data from our legacy system, etc... and I'm running into several issues that make me think maybe I shouldn't be using HEAD master or main (or whatever the default branch is called this week).

For one, the generated named.conf entries (see config_master.blade.php) have duplicate following section, and BIND ceremoniously refuses to even load with that:

    allow-query {
        any;
    };

Then, in generating MX records, or basically, anything with a priority, I see `Record:getResourceRecord()` doesn't even use the priority field of the record at all.  Seriously, how is this possible?  Without a prio you can't do MX, or NAPTR, or SRV, etc etc

One last thing, `ProBindPushDnsZones.php` does indeed push the zones but it doesn't restart BIND, to actually reload the `named.conf` and zonefiles.

I can provide examples, but this is all kind of obvious.  So obvious, I am wondering, am I in the wrong branch?

Thank you for your time.

**Comment by ericb-summit** [comment]
Also, `zone.blade.php` or some element in laravel escapes characters like double quotes, which are valid, and necessary for some NAPTR records.

**Comment by pacoorozco** [comment]
It's going to be fixed on `v0.12.2`.

**Comment by ericb-summit** [comment]
Hi Paco, I ran into a number of other issues that I fixed.  Should I add to this issue, or just open a PR?

**Comment by pacoorozco** [comment]
Hi

Please, open new ones. That way we can address them one by one.

Thanks
