### ISSUE TITLE
No way to update a zones serial

### ISSUE THREAD

**Issue by garethhumphriesgkc** [pacoorozco/probind#118]
**Describe the bug**
Once a zone is created, there's is no way to change it's serial number.  It can be viewed, but not edited.

**Comment by pacoorozco** [comment]
Serial number is updated every time you do a push to the DNS servers. 
**Is there any use case where you would like to update the serial number manually?**

**Comment by garethhumphriesgkc** [comment]
Did a little more testing - the serial updates correctly if `Use specific settings for this zone` is unchecked, but if it is checked the serial doesn't get changed on push, and can't be manually updated on the zone page.
