### ISSUE TITLE
Issue importing zone...

### ISSUE THREAD

**Issue by scramatte** [pacoorozco/probind#172]
Hi,

I've got **exception** when I try to import zone. 

Note that zone file is correct and I'm  running debian 11 + bind 9 

`Cannot construct an instance of ResourceRecordType using the value (string) `SOA`. Possible values are [A, AAAA, CNAME, MX, NAPTR, NS, PTR, SRV, TXT].`

Any idea what occurs here?

```
$TTL 38400      ; 10 hours 40 minutes
operativeit.es.          IN SOA  ns.nixus.es. hostmaster.nixus.es. (
                                2021111101 ; serial
                                10800      ; refresh (3 hours)
                                3600       ; retry (1 hour)
                                2419200    ; expire (4 weeks)
                                86400      ; minimum (1 day)
                                )
                        NS      ns3.nixus.es.
                        NS      ns4.nixus.es.

                        MX      1 mx0.mail.ovh.net.
                        MX      5 mx1.mail.ovh.net.
                        MX      50 mx2.mail.ovh.net.
                        MX      100 mx3.mail.ovh.net.

$ORIGIN operativeit.es.
...

```

**Comment by pacoorozco** [comment]
Sorry @scramatte I didn't see your PR before... you spotted perfectly the problem and fix it accordingly.
I'm going to merge my branch given it's adding tests to avoid this happens again.

The only thing I want to review is the `SPF` addition you have made in #174
