### ISSUE TITLE
Zone bulk import using the cli

### ISSUE THREAD

**Issue by scramatte** [pacoorozco/probind#173]
It would be nice to add laravel command to import whole directory of zones.

**Comment by scramatte** [comment]
I've tried it but with  reverse zone it doesn't works as this. 
Might it be possible to just specify file and let parser detect domain name?

**Comment by pacoorozco** [comment]
The parser can not guess the domain name unequivocally. It's depends on how you have built the zone file.

With the reverse zones you will need to modify the `Domain` line to build the domain name based on your file name. 

The script I was suggesting before is very dependent on your specific zone file naming. So it should be customized accordingly.
