### ISSUE TITLE
Where probind store zones files and

### ISSUE THREAD

**Issue by scramatte** [pacoorozco/probind#177]
Hello,

In my bind setup I've got following tree structure.   And multiple .conf files directly into /etc/bind/ . As I use view I've got various conf files and I include them in my named.conf

```
...
 include "/etc/bind/named.conf.internal";
 include "/etc/bind/named.conf.hint";
 include "/etc/bind/named.conf.public";
 include "/etc/bind/named.conf.reverse";
 include "/etc/bind/named.conf.ipv6";
...
```
 
```
/etc/
   bind/
      zones/
         master/
         slaves/

```

When you push  changes, In which dir probind store zones and which file does it edit to include  zones  (named.conf directly) ?

It would be nice to  have feature to group  zones  into distinct conf file to be   include file  proper view by hand.

**Comment by pacoorozco** [comment]
Hi!

Currently, `probind` will push the configuration and zone files to a remote folder using SFTP. The folder can be configured at **Settings > SSH Global Settings**.

The content of these files can be (a bit) customized using the [templates](https://github.com/pacoorozco/probind/blob/main/resources/views/templates/).

Once you have the files there, I usually run a custom script to copy and set them to fill my BIND's expectations.

Trying to configure BIND from this UI could be very challenging. The idea is that `probind` only takes care about the zone contents and the basic zone files inclusion in the BIND configuration.

**Comment by scramatte** [comment]
I've take a look to the templates that was the  missing part ... nice ! Thank you.

**Comment by pacoorozco** [comment]
Hi @scramatte 

I've just released a way to customize BIND configuration. Please take a look to [this documentation](https://github.com/pacoorozco/probind/blob/e15e67991902ba48ea0448d7838b0eb0448ef1c5/resources/bind-templates/README.md).

**WDYT**?
