### ISSUE TITLE
Handle $GENERATE directive for reverse zone

### ISSUE THREAD

**Issue by scramatte** [pacoorozco/probind#178]
I would nice to handle $GENERATE directive for reverse zone hostname automatic generation.

```
...
$GENERATE 1-254 $      IN      PTR     x-y-z-$-static.mycompany.es
...
```

**Comment by pacoorozco** [comment]
Hi @scramatte 

I've added a new feature which can be interesting for your use case. You will find the documentation [here](https://github.com/pacoorozco/probind/blob/8b808f711530925d6db1380f047b97b2dbfd8867/resources/bind-templates/README.md). 

It allows users to add specific templates for BIND zone file rendering. 

Imagine that you want to add the `$GENERATE` directive to an specific reverse zone `1.1.10.in-addr.arpa.`. You can create a new template (`resources/bind-templates/zones/1_1_10_in-addr_arpa.blade.php`) and add there the directives you want. 

**WDYT?**
