### ISSUE TITLE
Roles and Permissions to manage zones

### ISSUE THREAD

**Issue by scramatte** [pacoorozco/probind#179]
Hi,

It would nice Roles and Permissions to manage zones. 
Do you have something on the way else  may I can try to add such feature using Spatie Laravel Permision.

I already setup LDAP Authentication ,  I hope to be able to make PR soon.

Regards

**Comment by scramatte** [comment]
What I've got in mind is to be able to handle  granular permissions with multitenant support to let my customers to edit their domains themselves.   Roles above are correct  (might be superadmin will be required) but we need mechanism to bind domains to tenant and usernames to tenant.  Superadmin can access to everything for any tenant , and admin will be only for a tenant  for example.   Spatie permission achieve this very well ...

**Comment by pacoorozco** [comment]
The multi-tenant capability was not covered by `probind`. It doesn't only affect to zone access. It affects to the whole data model: servers, users, templates, pushes to servers...

Adding the concept of tenants means changing the DB completely... I don't think this tool is the right one to cover this use case and the amount of development seems huge 😓
