### ISSUE TITLE
Bulk update doesn't work

### ISSUE THREAD

**Issue by konachan700** [pacoorozco/probind#181]
ArgumentCountError
Too few arguments to function App\Jobs\UpdateZoneSerialName::__construct(), 0 passed in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 57 and exactly 2 expected
http://192.168.1.5/tools/push 

**To Reproduce**
1. get fresh installation
2. remove all examples
3. add one zone test.
4. run bulk update

**Expected behavior**

**Comment by pacoorozco** [comment]
Hi @konachan700 

Can you try again a let me know if it worked?
