### ISSUE TITLE
Change the SQL DATABASE information

### ISSUE THREAD

**Issue by sez76** [pacoorozco/probind#268]
Hello, 

I have a little question, where we can change the DB_PASSWORD ?

sez

**Comment by pacoorozco** [comment]
Hi @sez76 

As any Laravel application, the configuration is set on [an environment file](https://laravel.com/docs/9.x/#environment-based-configuration). 

We usually make a copy of the `.env.example` to `.env` and customize the configuration there.

**Comment by sez76** [comment]
Hi @pacoorozco 

Thank you very much :)

sez
