### ISSUE TITLE
Symphony error 

### ISSUE THREAD

**Issue by thermionic** [pacoorozco/probind#60]
**Describe the bug**
After completing the database page and logging in

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalErrorException in /var/www/vendor/symfony/translation/TranslatorInterface.php:24

**To Reproduce**
1. Clean install of Ubuntu 18.04/Ubuntu 20.04/Alpine 3.12 (reproducible on all three)
2. Install standard prerequisites (git, docker, docker-compose)
3. Create non root user
4. Add user to docker group
5. Follow Docker instructions from README.md (apart from running "docker-compose exec app php artisan migrate --seed", as that also errors)
6. As host that has had probind installed on is headless, go to http://hostname/install from desktop
7. Complete database page
8. Login with admin/secret

**Expected behavior**
To not see an error

**Comment by pacoorozco** [comment]
You're totally right, the composer is using a different PHP version (>7.2) than the docker (~7.1) that's why it's failing. Let me to review you PR @thermionic
