### ISSUE TITLE
TTL validation error when creating a new record

### ISSUE THREAD

**Issue by avsdev-cw** [pacoorozco/probind#66]
**Describe the bug**
When attempting to use a default TTL, a validation error occurs

**To Reproduce**
- Open a zone
- Create a new record
- Leave the TTL blank (description of the field says "Leave empty, to use default's TTL value (see Settings)")

**Expected behavior**
The default TTL should be used

**Screenshots**
![image](https://user-images.githubusercontent.com/25663960/93337264-d0909680-f820-11ea-9706-d9f50fc77ea0.png)

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser: Firefox
 - Version: 72.0.1

**Additional context**
Installed as per installation instructions

**Comment by pacoorozco** [comment]
Hi @avsdev-cw 

Thanks for raising this bug. It's fixed on `master` branch. I'm going to take a look to other bugs before publishing a new version.
