### ISSUE TITLE
Composer install fails with "Your lock file does not contain a compatible set of packages."

### ISSUE THREAD

**Issue by pentiumoverdrive** [pacoorozco/probind#80]
I'm following the instructions with installing composer, but I'm receiving this error:

> 
> Status: Downloaded newer image for docker.io/composer:latest
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Your lock file does not contain a compatible set of packages. Please run composer update.
> 
>   Problem 1
>     - rlanvin/php-ip is locked to version v2.0.0 and an update of this package was not requested.
>     - rlanvin/php-ip v2.0.0 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
>   Problem 2
>     - rlanvin/php-ip v2.0.0 requires ext-gmp * -> it is missing from your system. Install or enable PHP's gmp extension.
>     - badcow/dns v3.5.0 requires rlanvin/php-ip ~2.0 -> satisfiable by rlanvin/php-ip[v2.0.0].
>     - badcow/dns is locked to version v3.5.0 and an update of this package was not requested.
> 
> To enable extensions, verify that they are enabled in your .ini files:
>     - /usr/local/etc/php/php-cli.ini
>     - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
>     - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
> You can also run php --ini inside terminal to see which files are used by PHP in CLI mode.

**Comment by pacoorozco** [comment]
Hi @pentiumoverdrive 

The docker `composer` image was missing the `gmp` PHP extension. So it was not able to resolve the dependencies. I've modified the `app` docker image to include composer inside it. 

The `README` has been updated with the new guide to test **probind**.

Thanks for submitting the bug.
