### ISSUE TITLE
 export UID="$(id -u)" cannot be used since UID is read only and container is expected to run as non-root

### ISSUE THREAD

**Issue by telefax** [pacoorozco/probind#82]
The instructions says

```
export UID="$(id -u)"
```
Which on Centos 7 at least results in:
`-bash: UID: readonly variable`

and then docker-compose fails with:

```
Step 10/12 : RUN useradd --groups www-data,root --uid $DOCKER_UID --create-home $USER
 ---> Running in a0ac44e61fae
useradd: UID 0 is not unique
```
So two problems, UID exists already and reseting won't do any difference and 
the containers seems to be expected to run as non-root so the documentation needs to clarify this.
You could do something like this:

useradd docker-probind
export PROBIND_USER_UID=$(id -u docker-probind)

and update docker-compose.yml with PROBIND_USER_UID.
Then dont forget to chown -R the git directory with  PROBIND_USER_UID, depending on how you run your compose.

**Comment by pacoorozco** [comment]
The `UID` environment variable is readonly on `bash`, you're right! It looks like I'm not using `bash` 😅 .

So, I think it should be enough just changing the name of the `UID` variable. The second part of your comment is unclear to me. What the docker is doing is to create a user with the same `UID` than the one you have outside the docker, just to avoid to change file permissions.

Let me try it!

**Comment by pacoorozco** [comment]
It works! I've changed the exported variable. See it on master

**Comment by telefax** [comment]
I ran docker-compose as root and I still gets the same error, so I if I creae a new user account and chow to that user it works, otherwise just getting:

```
Step 10/12 : RUN useradd --groups www-data,root --uid $DOCKER_PROBIND_UID --create-home $USER
 ---> Running in c62fb3c1ada9
useradd: UID 0 is not unique
ERROR: Service 'app' failed to build: The command '/bin/sh -c useradd --groups www-data,root --uid $DOCKER_PROBIND_UID --create-home $USER' returned a non-zero code: 4
```
Probably because you cant create a root user inside a container

BTW,
You could add a few screenshots to convince people that it looks much much better than the old probind :-)

Good wok!

**Comment by pacoorozco** [comment]
Hi @telefax 

So you're trying to build the docker as `root` in your computer... Now I understand what the problem was :-D

I always propose not running anything as `root` unless it's needed 🤗
