### ISSUE TITLE
Error while pushing to bind servers

### ISSUE THREAD

**Issue by vanlueckn** [pacoorozco/probind#89]
Hello,

i have a fresh install of ProBind3 (latest release). I did not seed the database. I created one zone to try out the software. When i try to push to my dns servers, i get a 500 error response from my webserver.

The laravel log shows me the following error:
`[2021-01-19 17:21:40] local.ERROR: Argument 1 passed to App\Console\Commands\ProBINDPushZones::generateDeletedZonesContent() must be of the type array, object given, called in /var/www/...`

My server runs PHP 7.4.

**Comment by hopeday6688** [comment]
me too.

**Comment by pacoorozco** [comment]
I've seen the problem, let me work on it and add a test... apologies

**Comment by pacoorozco** [comment]
Issue has been fixed. It's still on the branch `issue-89`. I'm going to add documentation about how the DNS servers should be configured to work with ProBIND before merging it, this is not documented anywhere.

Feel free to use the branch to test the fix.
